apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: ClusterIP
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 5050
  selector:
    app: pgadmin