apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  ACCESS_TOKEN_SECRET: WU9VUl9TRUNSRVRfS0VZ
  REFRESH_TOKEN_SECRET: WU9VUl9TRUNSRVRfS0VZ